import React, { useEffect, useState, useMemo } from 'react';
import { createGrade, getGradesByStudent, getStudents, getAssignments } from './api';
import { Paper, Typography, TextField, Button, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, Box, Alert, MenuItem, Select, FormControl, InputLabel, Grid } from '@mui/material';
import { ResponsiveContainer, LineChart, Line, XAxis, YAxis, Tooltip, CartesianGrid, BarChart, Bar, Legend } from 'recharts';

export default function Grades({ token, user }) {
  const [grades, setGrades] = useState([]);
  const [form, setForm] = useState({ studentId: '', assignmentId: '', marks: '', remarks: '' });
  const [students, setStudents] = useState([]);
  const [assignments, setAssignments] = useState([]);
  const [queryStudent, setQueryStudent] = useState('');
  const [error, setError] = useState('');

  useEffect(() => { loadRefs(); }, [token]);

  async function loadRefs() {
    try{      const s = await getStudents(token); if (s.students) setStudents(s.students);      const a = await getAssignments(token); if (a.assignments) setAssignments(a.assignments);    }catch(e){}
  }

  const loadForStudent = async (studentId) => {    const res = await getGradesByStudent(token, studentId);    if (res.grades) setGrades(res.grades);    else setError(res.error || 'Failed to load grades');  };

  useEffect(() => {    // if logged-in student, auto-load their grades    if (user && user.role === 'student') {      (async () => {        try {          const s = await getStudents(token);          const my = s.students ? s.students.find(x => String(x.rollNumber) === String(user.username) || String(x.id) === String(user.id)) : null;          if (!my) { setError('Student record not found'); return; }          await loadForStudent(my.id);        } catch (e) { setError('Failed to load student grades'); }      })();    }  }, [user, token]);

  const handleSubmit = async (e) => {    e.preventDefault();    const payload = { studentId: form.studentId, assignmentId: form.assignmentId, marks: parseFloat(form.marks), remarks: form.remarks };    const res = await createGrade(token, payload);    if (res.grade) { setForm({ studentId: '', assignmentId: '', marks: '', remarks: '' }); setError(''); if (queryStudent) loadForStudent(queryStudent); }    else setError(res.error || 'Create failed');  };

  const handleLoad = async () => {    if (!queryStudent) return setError('Enter student ID');    setError('');    await loadForStudent(queryStudent);  };

  // Chart data: marks over assignments and distribution  const chartData = useMemo(() => {    if (!grades || grades.length === 0) return { trend: [], distribution: [] };    // trend: map grades to assignment titles    const trend = grades.slice().map(g => {      const a = assignments.find(x => String(x.id) === String(g.assignmentId));      return { name: a ? (a.title || `A-${a.id}`) : (`A-${g.assignmentId}`), marks: Number(g.marks) };    }).sort((a,b) => (a.name > b.name ? 1 : -1));    // distribution bins    const bins = { '0-39':0, '40-59':0, '60-79':0, '80-89':0, '90-100':0 };    grades.forEach(g => {      const m = Number(g.marks);      if (isNaN(m)) return;      if (m < 40) bins['0-39']++;      else if (m < 60) bins['40-59']++;      else if (m < 80) bins['60-79']++;      else if (m < 90) bins['80-89']++;      else bins['90-100']++;    });    const distribution = Object.keys(bins).map(k => ({ range: k, count: bins[k] }));    return { trend, distribution };  }, [grades, assignments]);

  return (
    <Box>
      <Typography variant="h5" gutterBottom>Grades</Typography>
      {error && <Alert severity="error">{error}</Alert>}

      {/* Admin/teacher: creation form and query controls */}
      {user && user.role !== 'student' && (        <Paper sx={{ p:2, mb:2 }}>          <form onSubmit={handleSubmit}>            <FormControl fullWidth margin="dense">              <InputLabel>Student</InputLabel>              <Select value={form.studentId} label="Student" onChange={e=>setForm({...form, studentId:e.target.value})}>                {students.map(s=> <MenuItem key={s.id} value={s.id}>{s.name} ({s.rollNumber||s.id})</MenuItem>)}              </Select>            </FormControl>            <FormControl fullWidth margin="dense">              <InputLabel>Assignment</InputLabel>              <Select value={form.assignmentId} label="Assignment" onChange={e=>setForm({...form, assignmentId:e.target.value})}>                {assignments.map(a=> <MenuItem key={a.id} value={a.id}>{a.title || a.id}</MenuItem>)}              </Select>            </FormControl>            <TextField label="Marks" value={form.marks} onChange={e=>setForm({...form, marks:e.target.value})} fullWidth margin="dense" />            <TextField label="Remarks" value={form.remarks} onChange={e=>setForm({...form, remarks:e.target.value})} fullWidth margin="dense" />            <Button type="submit" variant="contained" sx={{ mt:1 }}>Add Grade</Button>          </form>        </Paper>      )}
      {user && user.role !== 'student' && (        <Paper sx={{ p:2, mb:2 }}>          <Typography variant="subtitle1">View Grades by Student</Typography>          <Box sx={{ display: 'flex', gap: 1 }}>            <FormControl>              <InputLabel>Student</InputLabel>              <Select value={queryStudent} label="Student" onChange={e=>setQueryStudent(e.target.value)} sx={{ minWidth: 200 }}>                {students.map(s=> <MenuItem key={s.id} value={s.id}>{s.name} ({s.rollNumber||s.id})</MenuItem>)}              </Select>            </FormControl>            <Button variant="contained" onClick={handleLoad}>Load</Button>          </Box>        </Paper>      )}
      {/* Charts */}
      <Grid container spacing={2} sx={{ mb:2 }}>        <Grid item xs={12} md={8}>          <Paper sx={{ p:2, height: 300 }}>            <Typography variant="h6">Marks Trend</Typography>            <ResponsiveContainer width="100%" height="85%">              <LineChart data={chartData.trend} margin={{ top: 10, right: 30, left: 0, bottom: 0 }}>                <CartesianGrid strokeDasharray="3 3" />                <XAxis dataKey="name" />                <YAxis />                <Tooltip />                <Line type="monotone" dataKey="marks" stroke="#8884d8" activeDot={{ r: 8 }} />              </LineChart>            </ResponsiveContainer>          </Paper>        </Grid>        <Grid item xs={12} md={4}>          <Paper sx={{ p:2, height: 300 }}>            <Typography variant="h6">Marks Distribution</Typography>            <ResponsiveContainer width="100%" height="85%">              <BarChart data={chartData.distribution} layout="vertical">                <CartesianGrid strokeDasharray="3 3" />                <XAxis type="number" />                <YAxis dataKey="range" type="category" width={100} />                <Tooltip />                <Legend />                <Bar dataKey="count" fill="#82ca9d" />              </BarChart>            </ResponsiveContainer>          </Paper>        </Grid>      </Grid>
      {/* Table */}
      <TableContainer component={Paper}>        <Table>          <TableHead>            <TableRow>              <TableCell>ID</TableCell>              <TableCell>Student</TableCell>              <TableCell>Assignment</TableCell>              <TableCell>Marks</TableCell>              <TableCell>Remarks</TableCell>            </TableRow>          </TableHead>          <TableBody>            {grades.map(g=> (              <TableRow key={g.id}>                <TableCell>{g.id}</TableCell>                <TableCell>{ (user && user.role==='student') ? (user.name || user.username) : (students.find(s=>String(s.id)===String(g.studentId)) ? students.find(s=>String(s.id)===String(g.studentId)).name : g.studentId)}</TableCell>                <TableCell>{assignments.find(a=>String(a.id)===String(g.assignmentId)) ? assignments.find(a=>String(a.id)===String(g.assignmentId)).title : g.assignmentId}</TableCell>                <TableCell>{g.marks}</TableCell>                <TableCell>{g.remarks}</TableCell>              </TableRow>            ))}          </TableBody>        </Table>      </TableContainer>    </Box>  );
}